language: node_js
sudo: false
node_js:
  - 10
install:
  - npm install
  - npm install coveralls
script:
  - npm run test
  - npm run lint
  - jest --coverage --coverageReporters=text-lcov | coveralls

deploy:
  provider: script
  script: "cp .npmrc.template $HOME/.npmrc && npm publish"
  skip_cleanup: true
  on:
    tags: true
